t = int(input('Digite o numero desejado para aparecer a sua tabuada! '))
t0 = t*0
t1 = t*1
t2 = t*2
t3 = t*3
t4 = t*4
t5 = t*5
t6 = t*6
t7 = t*7
t8 = t*8
t9 = t*9
t10 = t*10
print('A tabuda de {} é: \n'
      '{}x0 = {}\n'
      '{}x1 = {}\n'
      '{}x2 = {}\n'
      '{}x3 = {}\n'
      '{}x4 = {}\n'
      '{}x5 = {}\n'
      '{}x6 = {}\n'
      '{}x7 = {}\n'
      '{}x8 = {}\n'
      '{}x9 = {}\n'
      '{}x10 = {}'.format(t, t, t0, t, t1, t, t2, t, t3, t, t4, t, t5, t, t6, t, t7, t, t8, t, t9, t, t10))